### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by SparklingComet** [ItsChriszz/Shops#1]
Hi, since you invited me, I guess you need help with something? I already looked at te code, but if you wish, I could clear some things up. Also a tip: save classes as .java files instead of Norma text files; this way syntax will automatically be highlighted. Furthermore, organise classes in packages like you do in your local workspace.

**Comment by ItsChriszz** [comment]
hello thank you for responding I need help with adding a custom config cause I want to add player shops but I can't figure out how to set the value in a custom config for the 1.4 dev file for now its set to the regular config but I want to add a playershops.yml file :)  

this was a thread I made with my alt so I pretty much got the answer but since I am still new I need help with the custom configs 
https://www.spigotmc.org/threads/stuck-on-a-issue-with-playershops.198235/#post-2064679

**Comment by SparklingComet** [comment]
You can add custom files:
File shops = new File(getDataFolder(), "playershops.yml");

**Comment by ItsChriszz** [comment]
Alright I will add that today thanks :)

**Comment by ItsChriszz** [comment]
So if I do   shop instead of this.getconfig it would be

Shop.getconfig ().set .().String.(blahblah)    that would be correct right?

**Comment by SparklingComet** [comment]
No, you need to create a YamlConfigurstion object:
YamlConfiguration yamlFile = YamlConfiguration.loadConfiguration(file);
where 'file' is a variable of type 'File'.
